language: cpp
os:
- linux
- osx
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports  # for cmake 3
    packages:
    - libcppunit-dev
    - g++-4.8
    - clang-3.7
    - cmake
    - cmake-data
install:
- if [ "`echo $CXX`" == "g++" ]     && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.8; fi
- if [ "`echo $CXX`" == "clang++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=clang++-3.7; fi
matrix:
  exclude:
  - os: osx
    compiler: gcc
script:
- mkdir build
- cd build
- cmake .. && make 
- cd ../test && ./simple_full_test.sh
env:
  global:
    - MAKEFLAGS="-j 4"
